apiVersion: v1
kind: Pod
metadata:
  name: kube-master
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
  - name: apiserver
    image: gcr.io/google_containers/hyperkube:{{ kube_release }}
    command:
    - /hyperkube
    - apiserver
    - --bind-address={{ kube_master_ip }}
    - --insecure-bind-address={{ kube_master_ip }}
    - --etcd-servers=http://{{ hostvars[inventory_hostname]['ansible_' + kubelet_bind_interface].ipv4.address }}:4001
    - --service-cluster-ip-range=10.255.0.1/24
    - --service-node-port-range=0-65535
    - --v=2
  - name: controller-manager
    image: gcr.io/google_containers/hyperkube:{{ kube_release }}
    command:
    - /hyperkube
    - controller-manager
    - --master={{ kube_master_ip }}:8080
    - --v=2
  - name: scheduler
    image: gcr.io/google_containers/hyperkube:{{ kube_release }}
    command:
    - /hyperkube
    - scheduler
    - --master={{ kube_master_ip }}:8080
    - --v=2
